main: com.sonorous.SonorousModels
name: SonorousModels
author: Sujan
version: 1.0.0
api-version: '1.20'
load: STARTUP
commands:
  SonorousModels:
    description: Your description
    usage: /<command>